### ISSUE TITLE
Image Viewing and Editing Issues in Caregiver Profile

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#1]
Caregivers are currently unable to:

View images for editing: Existing images in their profile are not displaying, preventing them from making changes.
Preview uploaded images: When attempting to upload new images, a preview is not shown, making it difficult to confirm the correct image is being selected.
This issue impacts the caregiver's ability to manage their profile effectively and could lead to frustration and a negative user experience.

Expected Behavior:

Caregivers should be able to view existing images clearly in their profile for editing purposes.
A preview of newly uploaded images should be displayed before saving changes.

Steps to Reproduce :

Log in as a caregiver.
Navigate to the profile section.
Attempt to edit an existing image or upload a new one.
Observe that images are not displayed or previewed.

Additional Information:

Screenshots: Attached
Priority: Medium (impacts core user functionality)

Please investigate and resolve this issue to ensure a smooth and positive experience for our caregivers.
![image viewing and editing caregivers](https://github.com/user-attachments/assets/9847a9cc-952f-40b5-b8a0-795994ec434e)

**Comment by yingw316** [comment]
test

**Comment by Kamal-Dixit** [comment]
Hey!!
I have tested this enhancement and observed that the caregiver is unable to preview newly uploaded images before saving the changes.
**Please refer to the attached screencast:**
https://kamalqa-yopmail.tinytake.com/msc/MTAzMzAyODlfMjQwMTY4NjM
Thank you
