### ISSUE TITLE
Remove Ticktock and Put X hyperlink 

### ISSUE THREAD

**Issue by yingw316** [Instacares247/Issues-tracker#14]
Remove Ticktock and Put X hyperlink 
![photo_2024-08-25_16-14-05](https://github.com/user-attachments/assets/62926ba3-2272-464d-991f-6f583537bdb1)

**Comment by Instacares247** [comment]
Confirmed: 
![image](https://github.com/user-attachments/assets/6665b012-5d8c-4c40-9b75-153398803583)
