### ISSUE TITLE
PUT warning "  use Computer to Signup only " no phones or tablets

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#19]
PUT warning "  use Computer to Signup only " no phones or tablets.  Let them know we working on the apps

**Comment by Instacares247** [comment]
If mobile is used, at least have a notice letting mobile or tablet users know it's preferred to use computer for signups.

**Comment by mdkamrulislam0093** [comment]
![image](https://github.com/user-attachments/assets/7d01dc47-b66c-42d5-9dd8-c045ebf752f0)

![image](https://github.com/user-attachments/assets/175ea9bb-cb1f-43ca-b784-2e243afc10c2)
