### ISSUE TITLE
Inconsistency in "Child's Experiences" Question

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#2]
Currently, in the question "Has your child experienced, or is currently experiencing any of the following?", it's possible to select both specific issues (e.g., "Speech delay," "Difficulty focusing") and the "None" option at the same time. This creates a logical inconsistency and could lead to inaccurate information being recorded about the child's health and development.

Expected Behavior:

Selecting the "None" option should automatically deselect any previously chosen specific issues.
Conversely, selecting any specific issue should automatically deselect the "None" option.

Impact:

This inconsistency can negatively impact the quality of information gathered during the onboarding process, potentially hindering the caregiver's ability to provide appropriate care and support to the child.

Priority: Medium (affects data accuracy and user experience)

Recommendation: Remove the 'none' option or Implement logic to ensure mutual exclusivity between the "None" option and the selection of specific issues in this question.

![health question](https://github.com/user-attachments/assets/8b370203-5f62-45a2-829a-dbc7f9c4d319)

**Comment by yingw316** [comment]
test
