### ISSUE TITLE
Caregivers Presentation Page need to CHANGE 

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#21]
![image](https://github.com/user-attachments/assets/2b1ce085-5870-4116-affc-a481d3181775)

1. Experienced
2. First Aid Certified
3. Background checked
4. ID Verified

**Comment by mdkamrulislam0093** [comment]
![card-single](https://github.com/user-attachments/assets/6bbfdea6-1491-4a28-be60-75bb1cbf36ba)

Please check single card page.
