### ISSUE TITLE
FIX CAREGIVERS ADDRESS 

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#22]
![image](https://github.com/user-attachments/assets/f8abeafe-b8b1-48c7-afa8-6de2ff2e5802)

To ensure accurate invoice and receipt delivery, I needed to address the issue that was brought up before with caregiver addresses in the Amelia booking database. I hoped Kamrul corrected addresses directly within Amelia, but this proved more complex than anticipated.

The appointment data also lacked essential details like caregiver email, phone # and physical addresses, making it unsuitable for generating invoices.

To overcome these obstacles, I've decided to utilize our financial database instead. While this approach may provide less booking-specific information, it crucially includes accurate email addresses for both parents and caregivers, guaranteeing that invoices and receipts reach the correct recipients.

This change requires me to dedicate extra time to adjust my VBA code, but it's a necessary step to ensure the reliability and accuracy of our invoicing process.

**Comment by mdkamrulislam0093** [comment]
Its fixed.

**Comment by mdkamrulislam0093** [comment]
[appointments (11).csv](https://github.com/user-attachments/files/17846399/appointments.11.csv)
