### ISSUE TITLE
Parents address need to be asked at registeration

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#23]
Parents address is very important to collect for invoice / receipt and tax purposes.

**Comment by mdkamrulislam0093** [comment]
![Parent-Signup-InstaCares-11-08-2024_09_29_PM](https://github.com/user-attachments/assets/91fb7273-e156-4a39-8b0e-1e0d53121cad)


Added. Please check here : 
https://www.instacares.xyz/parent-signup/

**Comment by Instacares247** [comment]
This address need to be linked to Amelia so we download the booking or finance csv, we can see it. Otherwise we can't issue invoices and receipts.

![image](https://github.com/user-attachments/assets/2c6be45b-7990-477e-8898-7c7e20f1d9d6)

**Comment by mdkamrulislam0093** [comment]
Completed

**Comment by Kamal-Dixit** [comment]
Hey!!
Tested the task and observed that the parent's address is now being requested on the registration page.
**Please consider the attached screenshot:**
https://github.com/user-attachments/assets/c15d30d2-0101-418b-8f21-99ea26242bd1
Thank you
