### ISSUE TITLE
Add the following on top of parents sign up page.

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#24]
Find Trusted Care for Your Child with InstaCares:

Free to Join: No membership fees.
Personalized Search: Find caregivers who match your needs, schedule, and budget.
Background Checks: Access verified caregiver profiles for peace of mind.
Easy Communication: Connect with caregivers, schedule interviews, and manage bookings seamlessly.
Secure Payments: Handle payments securely through the platform with automated receipts.
Sign up now and experience stress-free child care!

Questions? Call 289-880-5196, email [email address removed], or chat with us live!

**Comment by mdkamrulislam0093** [comment]
![Parent-Signup-InstaCares-11-08-2024_08_42_PM](https://github.com/user-attachments/assets/a55a157d-8c73-4e34-9f65-dfe1c1f23ca9)

Please check now.
https://www.instacares.xyz/parent-signup/
