### ISSUE TITLE
Parents getting logged out when clicking "Find Childcare"

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#26]
![WhatsApp Image 2024-10-27 at 21 32 40_85e78017](https://github.com/user-attachments/assets/cb4685f7-fc89-4712-a9a9-5c7ff79f421c)

To reproduce the issue: 
1. sign up as a caregiver
2. go to find childcare

for it to work 
1  i log in as parent 
2 i have to move the map and then it will work, if we don't move the map it will not work

**Comment by mdkamrulislam0093** [comment]
![Find-Childcare-InstaCares-11-08-2024_08_31_PM](https://github.com/user-attachments/assets/cafca13e-af1e-4eed-bf83-be71cfeb3459)

Can you please this. Its working now.

**Comment by Kamal-Dixit** [comment]
Hey!!
I have tested this issue and observed that the user remains logged in after clicking the 'Find Childcare' button.
**Please consider the attached screencast:**
https://kamalqa-yopmail.tinytake.com/msc/MTAzMjk4NjVfMjQwMTY0MjQ
Thank you

**Comment by Kamal-Dixit** [comment]
Hey !!
I have tested the issue and observed that the user remains logged in after clicking the 'Find Childcare' button. Additionally, verified that the map functionality is working as expected with no issues observed.
**Please consider the attached screencast:**
https://kamalqa-yopmail.tinytake.com/msc/MTAzMzAxNDJfMjQwMTY3MTU
Thank you
