### ISSUE TITLE
Upload Cancellation Policy to Key Pages

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#7]
Please add the following cancellation policy to the following pages on the InstaCares platform:

* Parents' home page
* Caregivers' home page
* Checkout page

**Content of the Policy:**

**InstaCares Refund Policy**

**1. Cancellations by Parents:**

* **More than 24 Hours Before Scheduled Service:** Full refund.
* **Less than 24 Hours Before Scheduled Service:** 50% refund.
* **No-Show:** No refund.

**2. Cancellations by Caregivers:**

* **Any Time Before Scheduled Service:** Full refund to the parent.
* **In Case of Emergency:** InstaCares will work with the parent to find a suitable replacement caregiver if possible. If a replacement cannot be found, a full refund will be issued.

**3. Modifications to Bookings:**

* **Subject to Caregiver Availability:** Changes to booking times or dates are subject to caregiver availability and may incur additional fees.
* **Refunds for Reduced Service:** If a booking is shortened, a partial refund may be issued at InstaCares' discretion.

**4. Exceptional Circumstances:**

* InstaCares reserves the right to issue full or partial refunds in exceptional circumstances, such as severe weather conditions or unforeseen events that prevent the service from being provided.

**Additional Considerations:**

* **On-Site Payment:** If your caregiver opted for on-site payment, we cannot guarantee the payment will be successful until it's completed on the day of service.

**Comment by mdkamrulislam0093** [comment]
Added Parents and Caregivers home page.
can you please send me a screenshot for checkout page?

**Comment by Instacares247** [comment]
Please make room on the left side of the booking page. make the fonts smaller to fit cancellation and refund policy to the left side. 

![image](https://github.com/user-attachments/assets/0db2b2aa-c5d4-42cf-af55-daa5a90bd282)

**Comment by Kamal-Dixit** [comment]
Hey !!
I have tested this task and observed that the InstaCares Refund Policy doesn't appear on the booking page. Additionally, a colon (':') needs to be added next to the 'Additional Considerations' section heading.
Please consider the attached screenshots:
https://github.com/user-attachments/assets/b06d0c88-38a1-468c-9d89-4982464472d9
https://github.com/user-attachments/assets/9b37368d-5bea-47db-9ca3-4f6344416f88
Thank you

**Comment by Instacares247** [comment]
![Capture](https://github.com/user-attachments/assets/f61fbc30-2080-4195-ad9f-ac4ead83976b)
This is done
