### ISSUE TITLE
Add Sign-Up Link to Sign-In Window

### ISSUE THREAD

**Issue by Instacares247** [Instacares247/Issues-tracker#9]
Currently, the sign-in window lacks a direct link to the sign-up page. Please add a "Sign Up" hyperlink that directs users to the registration page. This will improve the user experience for new users who need to create an account.

![image](https://github.com/user-attachments/assets/14fb3aa5-cb5b-40d1-bcec-5413a214dd8a)

**Comment by Instacares247** [comment]
also need the logo to redirect you to the home page. And caregiver and parenet sign up link.

**Comment by Kamal-Dixit** [comment]
Hey !!
I have tested this task and observed that the sign-in window currently, does not include a direct link to the sign-up page.
**Please consider the attached screenshot:**
https://github.com/user-attachments/assets/c5fa9e59-f2e8-4fad-b8f2-a8d8ce8828be

Thank you

**Comment by Instacares247** [comment]
LOGO click > goes to home page            |      instacares > go to sign  up page
